name: '동행복권 구매 액션'
description: '동행복권 사이트에서 복권을 구매한다.'
inputs:
  username:
    description: '동행복권 계정 ID'
    required: true
  password:
    description: '동행복권 계정 비밀번호'
    required: true
  telegram-bot-token:
    description: '결과를 발송할 텔레그램 봇 토큰'
    required: false
  telegram-chatid:
    description: '텔레그램 메시지를 수신할 아이디 (숫자), 내 아이디는 @userinfobot 에게 물어보면 알 수 있다.'
    required: false
  lo40:
    description: '로또 구매 수량'
    required: false
    default: '1'
  lp72:
    description: '연금복권 구매 수량'
    required: false
    default: '1'

runs:
  using: 'docker'
  image: 'docker://ryube/lottery-agent:v1'
  env:
    DHL_USERID: ${{ inputs.username }}
    DHL_PASSWORD: ${{ inputs.password }}
    TLG_BOTTOKEN: ${{ inputs.telegram-bot-token }}
    TLG_CHATID: ${{ inputs.telegram-chatid }}
  args:
  - buy
  - --lo40
  - ${{ inputs.lo40 }}
  - --lp72
  - ${{ inputs.lp72 }}

branding:
  icon: gift
  color: blue
